[project]
name = "rzil-compiler"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
  "colorama>=0.4.3",
  "lark~=1.1.9",
  "setuptools~=80.8.0",
  "pcpp~=1.30",
  "tqdm~=4.66.4",
]
