# SPDX-FileCopyrightText: 2022 Rot127 <unisono@quyllur.org>
# SPDX-License-Identifier: LGPL-3.0-only

transform_test = [
'{         EA = (HEX_REG_ALIAS_SP) + -8;    ; mem_store_u64(EA, (((((uint64_t)((HEX_REG_ALIAS_LR))) << 32) | ((uint32_t)((HEX_REG_ALIAS_FP)))) ^ (((uint64_t)(HEX_REG_ALIAS_FRAMEKEY)) << 32))); (HEX_REG_ALIAS_FP = EA);; ; (HEX_REG_ALIAS_SP = EA-uiV);; }',
    ]


euclid_instructions = [
    'A4_ext',
    'A2_tfrsi',
    'A2_sub',
    'A2_combinew',
    'J2_call',
    'C2_cmpgtu',
    'M2_mpyi',
    'S2_storerd_io',
    'A2_combineii',
    'SS2_storew_sp',
    'SL2_loadrd_sp',
    'C2_cmpgti',
    'A2_tfr',
    'S2_cl0',
    'A2_paddfnew',
    'L2_loadrd_io',
    'J2_jumpr',
    'A2_nop',
    'SS2_stored_sp',
    'SS2_allocframe',
    'S2_storeri_io',
    'L4_return',
    'J2_loop0r',
    'A2_addi',
    'A2_abs',
    'S4_storeiri_io',
    'S2_lsr_i_vw',
    'A2_psubfnew',
    'SA1_seti_undocumented',
    'SA2_tfrsi',
    'S2_lsl_r_vw',
    'J2_jumpt',
    'J2_jumpf',
    'J2_jump',
    'SA1_tfr',
    'SA1_combine1i',
    'SA1_seti',
    'SL2_jumpr31_t',
    'J2_jumprt',
    'J2_jumprf',
    'C2_xor',
    'C2_muxii',
    'A2_subri',
    'A2_paddit',
    'J4_cmpgti_tp0_jump_t',
    'SL2_loadrh_io',
    'SL1_loadri_io',
    'SA1_seti',
    'SS2_storeh_io',
    'SA1_addi',
    'SA1_combinezr',
]
